version: '3.9'

networks:
  shared_net:
    driver: bridge

volumes:  # ✅ Added missing volume declaration
  pgadmin_data:
  npm_data:
  npm_letsencrypt:
  portainer_data:

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mpwt.org
      PGADMIN_DEFAULT_PASSWORD: cbO5)\H_X62l
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - shared_net

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - shared_net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - shared_net
